/**
 * بیلد اسکریپت — الگوی BPB
 * ۱) صفحات HTML (login/install/panel) + CSS/JS با placeholder تزریق و مینی‌فای می‌شوند
 *    → src/generated/assets.ts
 * ۲) همه‌چیز با esbuild در یک فایل dist/_worker.js باندل می‌شود
 */
import { build, context } from 'esbuild';
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync, rmSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { minify as minifyJs } from 'terser';

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'));
const ASSETS_DIR = join(ROOT, 'src/assets');
const OUT_DIR = join(ROOT, 'src/generated');
const OUT_FILE = join(OUT_DIR, 'assets.ts');

const watch = process.argv.includes('--watch');

/** پردازش assets → ماژول TS */
async function buildAssets() {
  const sharedCssPath = join(ASSETS_DIR, 'shared.css');
  const sharedCss = existsSync(sharedCssPath) ? readFileSync(sharedCssPath, 'utf8') : '';

  const dirs = readdirSync(ASSETS_DIR, { withFileTypes: true }).filter((d) => d.isDirectory());
  const assets = {};

  for (const d of dirs) {
    const base = join(ASSETS_DIR, d.name);
    const indexPath = join(base, 'index.html');
    if (!existsSync(indexPath)) continue;

    let html = readFileSync(indexPath, 'utf8');
    html = html.replace('/* SHARED_CSS_PLACEHOLDER */', () => sharedCss);

    // فونت امبدشده فقط برای پنل (برای حجم باندل)
    const fontCssPath = join(ASSETS_DIR, 'font.css');
    if (existsSync(fontCssPath)) {
      html = html.replace('/* FONT_PLACEHOLDER */', () => readFileSync(fontCssPath, 'utf8'));
    }
    html = html.replace('/* FONT_PLACEHOLDER */', () => '');

    const cssPath = join(base, 'style.css');
    if (existsSync(cssPath)) {
      html = html.replace('/* CSS_PLACEHOLDER */', () => readFileSync(cssPath, 'utf8'));
    }

    const jsPath = join(base, 'script.js');
    if (existsSync(jsPath)) {
      const { code } = await minifyJs(readFileSync(jsPath, 'utf8'), { format: { comments: false } });
      html = html.replace('/* JS_PLACEHOLDER */', () => code);
    }

    html = html.replace(/__VERSION__/g, pkg.version);
    assets[d.name] = html;
  }

  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(
    OUT_FILE,
    `// auto-generated by scripts/build.mjs — do not edit\nexport const ASSETS = ${JSON.stringify(assets)} as const;\n`,
  );
  console.log(`📄 assets → ${Object.keys(assets).join(', ')}`);
}

const options = {
  entryPoints: ['src/worker.ts'],
  bundle: true,
  format: 'esm',
  target: 'es2022',
  outfile: 'dist/_worker.js',
  minify: !watch,
  sourcemap: false,
  legalComments: 'none',
  define: {
    __VERSION__: JSON.stringify(pkg.version),
  },
  // ماژول‌های داخلی Cloudflare — نباید باندل شوند
  external: ['cloudflare:sockets'],
};

rmSync('dist', { recursive: true, force: true });
await buildAssets();

if (watch) {
  const ctx = await context(options);
  await ctx.watch();
  console.log('👀 watching src/ — هر تغییر، بیلد مجدد می‌سازد...');
} else {
  await build(options);
  const size = statSync('dist/_worker.js').size;
  console.log(`✅ dist/_worker.js (${(size / 1024).toFixed(1)} KB)`);
}
