import { chromium } from 'playwright';
const browser = await chromium.launch({ args: ['--no-sandbox', '--disable-dev-shm-usage', '--disable-gpu'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
page.on('pageerror', (e) => console.log('PAGEERROR:', e.message.slice(0, 200)));
page.on('console', (m) => { if (m.type() === 'error') console.log('CONSOLE:', m.text().slice(0, 200)); });
await page.goto('https://qanat-admin.amirhesamfathalian7.workers.dev/panel', { waitUntil: 'load' });
await page.waitForTimeout(1000);
console.log('login screen visible:', await page.isVisible('#loginScreen'));
await page.fill('#passInput', process.env.ADMIN_PASS);
await page.click('#loginBtn');
await page.waitForTimeout(2500);
console.log('login screen still visible:', await page.isVisible('#loginScreen'));
console.log('nav visible:', await page.isVisible('#appNav'));
console.log('cookie:', await page.evaluate(() => document.cookie));
const r = await page.evaluate(async () => {
  const res = await fetch('/panel/api/login', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ password: document.getElementById('passInput').value }) });
  return { status: res.status, body: await res.text() };
});
console.log('direct login fetch:', JSON.stringify(r));
await browser.close();
